### ISSUE TITLE
Reason fixing ruby version and update process unclear 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmorganiser.github.io#19]
* What is the reason to pin this repo to a specific ruby version?  
 https://github.com/rdmorganiser/rdmorganiser.github.io/blob/e3d9bc6b625f045835a204495de129c01f5622ed/.ruby-version
*  If there is none we should make sure always using the latest version

**Comment by jochenklar** [comment]
The reason is: to make live easier. I use rbenv to run jekyll, but it *should* work with any recent ruby version. Any problem with a particular ruby version?

**Comment by jmfrenzel** [comment]
Testing locally  `.ruby-versionfile`  is of help.  Since my initial comment the   `.ruby-versionfile` is not provided  with this repository.   

In the github action we use  a fixed version https://github.com/rdmorganiser/rdmorganiser.github.io/blob/master/.github/workflows/pages.yml  which is fixed to  ruby 3.0. 

Closing this issue for now
